# Generated by Django 6.0.4 on 2026-04-07 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_estoque', models.IntegerField(verbose_name='Quantidade em Estoque')),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Custo')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Venda')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoTabelado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição do Serviço')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ex: Desktop, Notebook, Impressora', max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=100, verbose_name='Número de Série')),
                ('especificacoes', models.TextField(verbose_name='Especificações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('data_previsao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Previsão')),
                ('defeito_relatado', models.TextField(verbose_name='Defeito Relatado')),
                ('laudo_tecnico', models.TextField(blank=True, null=True, verbose_name='Laudo Técnico')),
                ('status', models.CharField(default='Aguardando Avaliação', max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('ordem_de_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.ordemdeservico')),
                ('peca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.peca')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.servicotabelado')),
            ],
        ),
    ]
